gschup/ggrs

Cargo.toml, examples/rapier/rapier_synctest.rs, src/network/udp_protocol.rs
Calling std::time::Instant::now() causes a panic on wasm.
The instant crate tries to emulate std::time::Instant on wasm, and is a
type alias to std::time::Instant otherwise.
=> fix: Fix panic due to std::time::Instant::now() on wasm

src/lib.rs, src/network/non_blocking_socket/mod.rs, src/network/non_blocking_socket/udp_socket.rs, src/network/udp_protocol.rs, src/sessions/p2p_session.rs, src/sessions/p2p_spectator_session.rs
The session constructors now accept a boxed existing NonBlockingSocket object instead of creating sockets themselves.
=> refactor: Turn NonBlockingSocket into trait to allow alternate socket types

src/sync_layer.rs
it was at first panicking because the input frame didn't match up with the current frame. now it correctly panics when hitting the prediction threshold.
=> Fixed faulty test:  sync_layer::test_reach_prediction_threshold()

src/network/protocol.rs
Thanks to fu5ha from https://github.com/gschup/ggrs/pull/41#discussion_r1021007805
=> fix: removed an allocation in `InputBytes::zeroed`

src/lib.rs, src/network/messages.rs, src/network/protocol.rs, src/sessions/builder.rs, src/sessions/p2p_session.rs
These changes refer to #46  
**What has been done**
I found this feature also useful for my personal project.
Currently its sends ChecksumReports at an specified rate to the other peers and whenever a discrepancy is found, it sends a DesyncDetected event to the user with information such as the given frame, mismatched checksums and the remote peer address.
**I seek help in**
Maybe the improvement of any codestyle or patterns .
How should I handle the rate of events? currently it sends an event at every chance it gets if a desync is found.
~~How should I incorporate this so this becomes a feature the user can opt-in for.~~
**How did I test this**
I made 2 builds of the ex_game example one with higher movement speed than the other.
=> feat: DesyncDetection For P2PSessions

.github/workflows/rust.yml, Cargo.toml
ggrs doesn't currently build for wasm. Adding a check that it doesn't go by unnoticed in the future.
Adapted the setup I use in Matchbox. Not sure if there's a big difference between running on windows contra ubuntu?
=> Fix wasm build and add ci check

.github/workflows/rust.yml
Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.5.0
> - Add new public key for known_hosts
>
> ## v3.4.0
> - Upgrade codeql actions to v2
> - Upgrade dependencies
> - Upgrade @actions/io
>
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - Upgrading version to 3.2.0
>
> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add …
=> chore: update actions/checkout in GitHub Actions workflows to v3

.github/workflows/rust.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/gschup/ggrs/actions/runs/4589836542:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct invocations of `cargo`.
=> chore: replace unmaintained actions-rs/* actions in CI workflows

examples/README.md, examples/ex_game/ex_game.rs
Added a function in the examples to trigger a desync by moving player 1 to the origin in local session only. This will create a desync which can be useful to simply see and understand the output. Maybe you don't want to merge this, but I think it's quite useful for people to quickly see how a desync will be detected (otherwise it's quite hard to get an actual desync).
You possibly want to change the way the function is called.
=> Allow player to trigger desync on purpose in examples

examples/ex_game/ex_game_p2p.rs, src/network/protocol.rs, src/sessions/builder.rs, src/sessions/p2p_session.rs, src/sync_layer.rs, tests/test_p2p_session.rs
Fixes #63 and also fixes a bug that checksums are removed prematurely if the interval is > `MAX_CHECKSUM_HISTORY_SIZE`
Confirmed working with the test case for #63 
Bonus: Remote checksums are now only checked once (removed once verified).
=> Fix false positives in remote desync detection

src/sync_layer.rs
Easily printing a cell's frame and checksum can be very useful when debugging.
Can also be very handy for bevy_ggrs to add some more info to `debug!` tracing levels.
=> Implement `Debug` for `GameStateCell`

CHANGELOG.md, examples/ex_game/ex_game.rs, examples/ex_game/ex_game_p2p.rs, examples/ex_game/ex_game_spectator.rs, src/error.rs, src/lib.rs, src/network/protocol.rs, src/sessions/builder.rs, src/sessions/p2p_session.rs, src/sessions/p2p_spectator_session.rs, src/sessions/sync_test_session.rs, src/sync_layer.rs, tests/stubs.rs, tests/stubs_enum.rs, tests/test_p2p_session.rs, tests/test_p2p_spectator_session.rs, tests/test_synctest_session.rs, tests/test_synctest_session_enum.rs
To prepare for the next release, it's time to introduce breaking changes!
According to the [rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html#:~:text=In%20UpperCamelCase%2C%20acronyms%20and%20contractions%20of%20compound%20words%20count%20as%20one%20word%3A%20use%20Uuid%20rather%20than%20UUID%2C%20Usize%20rather%20than%20USize%20or%20Stdin%20rather%20than%20StdIn.), Acronyms should not be fully uppercase. We already do this in bevy_ggrs, now it is time to also implement that change here.
- Renamed `GGRSError` to `GgrsError`
- Renamed `GGRSEvent` to `GgrsEvent`
- Renamed `GGRSRequest` to `GgrsRequest`
- Also removed deprecated and unused `GgrsError` variants
=> Refactor: naming conventions

src/error.rs, src/sessions/sync_test_session.rs
And also report all mismatched frames, not just the first one.
This makes it much easier to debug desyncs, as it tells you exactly which frame(s) you should look into.
Synctest checksum errors now look like this:
```
Detected checksum mismatch during rollback on frame 308, mismatched frames: [305, 306]
```
=> Report which frames checksums failed for in synctest sessions

Cargo.toml
Hello 👋 
[Bones](https://github.com/fishfolk/bones), the meta-engine built on Bevy that powers [jumpy](github.com/fishfolk/jumpy), is trying to reduce its dependencies. Currently we have a dependency on versions `0.11` and `0.12` of `parking_lot` and this upgrade would help us slim down.
- Update `parking_lot` from `0.11` to `0.12` (see [the changelog](https://github.com/Amanieu/parking_lot/blob/master/CHANGELOG.md#parking_lot-0120-parking_lot_core-090-lock_api-046-2022-01-28))
=> update parking_lot to 0.12

examples/ex_game/ex_game_p2p.rs, src/input_queue.rs, src/network/compression.rs, src/network/protocol.rs, src/sessions/builder.rs, src/sessions/p2p_session.rs, src/sessions/sync_test_session.rs, src/sync_layer.rs, tests/stubs_enum.rs
Fixes several bugs in the sync layer / input_queue logic. This now allows for max_prediction_window to be set to 0 and thus falling back to lockstep netcode (with unnecessary gamestate save requests).
=> Fix/Feature: Lockstep

Cargo.toml
Bump the example game to the latest macroquad version. There aren't any API changes that affect the demo so this is just a straightforward Cargo.toml change.
---
Macroquad 0.4 has been out for a bit now, and for whatever reason 0.4 compiles fine but 0.3 gets a linking error on my system. The linking error is almost certainly resolvable via installing the right system package dependencies etc, but bumping to Macroquad 0.4 has already fixed it, so I figure why not PR that to save someone else the hassle.
* Only tested on Linux (Fedora 40)...
* But I use Macroquad 0.4 for [my own](https://www.slowrush.dev/pixel-wizards-game/) game and that runs fine on Windows so I expect this will be just fine there too.
* Macroquad 0.4 did change a few things in MacOS land (a new Metal backend is …
=> Bump example game macroquad to 0.4

CHANGELOG.md, src/frame_info.rs, src/lib.rs, src/sync_layer.rs
It turns out that the restriction of only storing cloneable things in `GameStateCell` is not actually necessary, since it's trivial for client code to do the actual cloning of the data stored in `GameStateCell` if they have access to it.
For convenience, to avoid breaking API, and to steer users away from the footgun of modifying a stored state, we still provide a `load()` function for the case where `T` is `Clone`.
---
This was originally motivated by me needing to clone a type which is faster to clone if I have a mutable reference to it; I could have used interior mutability via `UnsafeCell` but just out of interest I tried seeing if ggrs's `Clone` bound for game state could be relaxed, and it turns out that it can.
It seemed like a change that might be worth upstreaming since it …
=> feat: Remove GameStateCell's T: Clone requirement

CHANGELOG.md, src/sessions/p2p_spectator_session.rs, src/sessions/sync_test_session.rs
`current_frame()` exists for p2p session currently, but the matching functions are missing for synctest or spectator sessions, so this adds them.
---
Adding these functions makes it easier to make a wrapper that abstracts over all types of sessions.
=> Expose current frame in synctest and spectator sessions

CHANGELOG.md, src/sessions/p2p_session.rs
What it says on the tin.
---
Useful so I can calculate the checksum for game frames only when it's strictly necessary to have a checksum calculated.
I could instead store what I had set as the desync detection mode myself, but this is neater.
=> Allow reading P2PSession's current desync detection mode

CHANGELOG.md, src/sessions/p2p_session.rs
This fixes the case where the following happens:
1. Sync layer requests roll back to frame N
2. Sync layer requests advance to frame N+1
3. Sync layer marks frame N as confirmed
4. P2pSession's desync detection decides to send a checksum for frame N to peers, even though the checksum for frame N is now known to be incorrect (because ggrs-consuming-code has not had a chance to act on the advance frame request, so the checksum stored in frame N is from before the rollback).
5. Peers receive the incorrect checksum and flip out thinking there is a desync.
Actually causing this bug to reliably manifest in practice is somewhat tricky; I was able to reliably do it in my game via the following:
* high latencies (150ms on each client network interface, so 300ms round trip)
* input delay == 0
* …
=> Fix desync detection false positive caused by a rollback

Cargo.toml, examples/ex_game/ex_game.rs, src/frame_info.rs, src/input_queue.rs, src/lib.rs, src/network/protocol.rs, src/sync_layer.rs, tests/stubs.rs, tests/stubs_enum.rs
(from commit msg)
Remove the bytemuck bounds on Config::Input, and replace them with Default and Serialize + DeserializeOwned.
1. Default is a less strict bound than Zeroable, and it's all we need - so it's more ergonomic.
2. NoUninit + CheckedBitPattern are also fairly stringent requirements, but it turns out that the only place that we actually rely on them is when we serialize or deserialize the input type. So we can just rely on the relevant Serde trait bounds instead, which again is more ergonomic.
Both changes are backwards incompatible, though they should be quite easy to resolve for existing users of GGRS (unless they have a philosophical objection to using Serde directly, I suppose).
However, number 2 does have some significant tradeoffs associated with it; in order of least to …
=> RFC: feat: Input type must be Default+Serde but not POD

CHANGELOG.md, src/network/messages.rs, src/network/protocol.rs
fixes #35 - see discussion there, particularly [my latest comment](https://github.com/gschup/ggrs/issues/35#issuecomment-2543140981) for some reasoning on why I'm clamping to i16 instead of clamping to i8 or clamping to i32.
In case it isn't clear from that comment, I think clamping to i8 or i32 would be fine too - the main thing is to avoid crashing :)
=> fix: avoid panicking when local frame adv exceeds i8 range

CHANGELOG.md, examples/ex_game/ex_game.rs, examples/ex_game/ex_game_p2p.rs, examples/ex_game/ex_game_spectator.rs, examples/ex_game/ex_game_synctest.rs, src/sessions/builder.rs, src/sessions/p2p_session.rs, src/sync_layer.rs
NB: This builds on PR #82 so we better merge that one first to make this diff easier to review. (is Github working on [stacked diff](https://www.stacking.dev/) support yet?)
---
This fixes several issues that (I am fairly certain) came from merging #79:
* When at the limit of the prediction window, rolling back would crash. This is fairly easy to trigger by adding a lot of latency in a network simulator. The cause was an off by one error in SavedStates' calculation of how many states need to be saved.
* Clearer logic controlling when it's okay to request advancing the frame. I am not 100% certain but I suspect that the #79 logic wasn't handling `NULL_FRAME` correctly? In any case I think this new structure makes it a lot easier to reason about.
* Lockstep mode specific stuff:
* Document …
=> Fix max rollback and lockstep handling

CHANGELOG.md
Forgot to include this in #82, and I figured it's a big enough change that it's worth raising a separate PR for.
This is the first "item with sub items" entry in the changelog, looks like, but when I tried to write it all as one bullet then it just became too hard to read. Feel free to reword/edit/etc when you cut the release if you don't like the multiple bullets.
=> Add changelog entry for bytemuck removal

Cargo.toml, examples/ex_game/ex_game_p2p.rs, examples/ex_game/ex_game_spectator.rs, examples/ex_game/ex_game_synctest.rs, src/network/messages.rs, src/network/protocol.rs, src/network/udp_socket.rs, src/sessions/p2p_session.rs
Closes #89.
I already had 90% of this implemented on my ggrs fork so I figured I'd just push it up and see if you were happy to go with `tracing` as the log choice. (If you prefer using `log`'s API instead, I'm happy to rework this to do that instead.)
Summary of changes:
* Add tracing dependency to library, and tracing_subscriber + tracing_log for dev deps so we can use them in examples and have all logs going to one place. (Importantly, we need to use tracing_log and turn on macroquad's log_rs feature to ensure that macroquad's logs - which includes our info!/etc logs because we import macroquad's prelude - get routed to tracing)
* Fix the specific cases mentioned in #89 :
* Fix the println in advance_frame()
* Don't panic in debug mode on large UDP packet sizes anymore - just warn!() …
=> Add tracing for logging

src/network/protocol.rs, tests/test_p2p_session_enum.rs
The code for setting up the input buffers currently causes a crash when getting enums for input because it calculates the size of the input using `core::mem::size_of()` instead of bincode, which have different results. I wrote a new test to demonstrate the issue. Without the changes in this PR, it panics:
By updating the initial size to use bincode::serialized_size(&T::Input::default()), the problem is fixed. This does not solve for cases when the enum variants have data and are encoded to different sized, which would require a much larger change.
=> Allow simple enums in Input
